### ISSUE TITLE
Readability suggestion

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/hypha.coop#10]
Readability suggestion from @Connoropolous:

- https://twitter.com/Connoropolous/status/1252754151232151554
    >For the purple text increasing the line height would help reading a lot.
For the lower text here, adding a layer in between the text and the green pixels would help a lot with reading there too :)

**Comment by patcon** [comment]
Already added white background on text in front of green dot things.

@benhylau raised independantly that the green dots in general feel a bit jarring.
