### ISSUE TITLE
Refine the hiring process

### ISSUE THREAD

**Issue by rkashe** [hyphacoop/hypha.coop#189]
Re-ticketed from https://github.com/hyphacoop/handbook/issues/163 

Success criteria: Produce a hiring workflow and post it to the handbook.

Create text to include in job posts re: only selected candidates will be contacted, etc.

What tools can we use to make the hiring process more manageable, especially when there are a high number of candidates to sort through.

Best websites to share technical job positions.

**Comment by writerly03** [comment]
Some of this information is captured in the hiring template: https://docs.google.com/spreadsheets/d/1MaGsFYuT2qDL8Bv88nsshNCjiMUPG9mN6YB93LBD6JA/edit#gid=387667907

**Comment by writerly03** [comment]
I'm confused about the status of this issue. Hence re-adding. Please move to Done if it's done?

**Comment by tripledoublev** [comment]
Closing this since it is not in the right repo
