### ISSUE TITLE
Adjust Activity Pub configs to include dripline and cosmos

### ISSUE THREAD

**Issue by tripledoublev** [hyphacoop/hypha.coop#231]
Making progress on the Activity Pub integration;
- ✔️ AP Inbox creation success 
- ✔️ Github action commits [_data/activity_pub.yml](https://github.com/hyphacoop/hypha.coop/commit/888530dc30f9ebe59f3bfed858e7b221ecff6d37#diff-7dcb88a9af20bde788dd74e1ad2571be483f84d46dbb4d0d13d6d965b8f76f9a)

I noticed in the commit linked above that the notifications only include `Hypha Does Cosmos`.
I believe this is due to incomplete settings in _config.yml

- [x] Fix _config.yml to include Dripline posts
- [x] Consider renaming the inbox to HyphaCoop instead of Dripline to include all activity under one account

Question;
Would it be preferred to create two accounts and keep notifications separate for `Dripline` and `Hypha Does Cosmos`

**Comment by fauno** [comment]
>  Would it be preferred to create two accounts and keep notifications separate for Dripline and Hypha Does Cosmos

We can test this when https://github.com/hyphacoop/social.distributed.press/issues/15 is implemented, because you'd need two actors (ie `@dripline@hypha.coop` and `@cosmos@hypha.coop`)
