### ISSUE TITLE
Reconsider aesthetic of green dots for visibility

### ISSUE THREAD

**Issue by patcon** [hyphacoop/hypha.coop#25]
Re-ticketed from @benhylau comment in https://github.com/hyphacoop/hypha.coop/pull/18#issuecomment-784803729

> I actually think the site without the green dots is a lot more readable. Maybe I am staring at the screen too much but the green dots make it straining to try to actually read the text @garrying I really hope we can make it not cut into the text, esp for narrow screen

**Comment by patcon** [comment]
Realized this wasn't tagged as @hyphacoop/business-planning-wg, but we make exec decision to close these aesthetic concerns, right?

**Comment by Shrinks99** [comment]
These aren't used anymore! ;)
