### ISSUE TITLE
Fix Open Graph metadata on dripline pages

### ISSUE THREAD

**Issue by patcon** [hyphacoop/hypha.coop#28]
Re: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fhypha.coop%2Fdripline%2Fhow-we-co-operate%2F

Seems that the current og:meta points from dripline post pages back to root url, and so the metadata is for that page instead of the titled post page

<img width="789" alt="Screen Shot 2021-02-25 at 3 45 00 PM" src="https://user-images.githubusercontent.com/305339/109214911-6d684000-7780-11eb-82ae-1129f7380724.png">

**Comment by dcwalk** [comment]
I can't reproduce the things in that screenshot RE: this behaviour, but will make a minor tweak to improve signalling for being on Dripline page + url

![Screenshot_2021-09-10_09-56-48](https://user-images.githubusercontent.com/4692834/132864804-8532d861-6788-4c43-8202-58cd44c3c3c7.png)

**Comment by dcwalk** [comment]
I can't reproduce this behaviour, but will make a minor tweak to improve signalling for being on Dripline page

![Screenshot_2021-09-10_09-56-48](https://user-images.githubusercontent.com/4692834/132864804-8532d861-6788-4c43-8202-58cd44c3c3c7.png)
