### ISSUE TITLE
contact quickbooks customer service to be added in the account

### ISSUE THREAD

**Issue by abbasaliqambar** [hyphacoop/hypha.coop#281]

**Comment by abbasaliqambar** [comment]
contact customer support and provide reference number 25625

![Image](https://github.com/hyphacoop/hypha.coop/assets/160063413/671d5c0e-523b-4c5b-a681-04eeb93b280a)

**Comment by abbasaliqambar** [comment]
@YurkoWasHere I called Quickbooks customer service, and had a screen share with them. They have no idea why I am unable to add myself to it. They have created a ticket and will get back to me with a solution

**Comment by tripledoublev** [comment]
Closing the issue as it was created in the wrong repository
