### ISSUE TITLE
Create HUB Accounting Reporting Template for the Calendar Year 2024

### ISSUE THREAD

**Issue by abbasaliqambar** [hyphacoop/hypha.coop#282]
To create a basic Quarterly Financial Reporting Template consisting of

Income Statement
Balance Sheet
Cash Flow Report

Data can be picked from :
Folder: https://drive.google.com/drive/folders/1b1Tfin98mNcfSdG7uVI4SXP9JA5pVaJz
https://docs.google.com/spreadsheets/d/16B4IwO7JA3rSO6hBVjvT-dVUg484XcwWiDtlYGVLOog/edit#gid=0
https://docs.google.com/spreadsheets/d/1RSJB2JcNE35vHs4SgZOr5tPAb4i1hyx0aaj3VINm5AY/edit?pli=1#gid=0

**Comment by tripledoublev** [comment]
Closing the issue as it was created in the wrong repository
