### ISSUE TITLE
Link typo in ISLE Dripline post

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/hypha.coop#360]
https://github.com/hyphacoop/hypha.coop/blob/578f7a1bb7f5fb6ee038e2dd204ff051a59ba7ae/_posts/2024-07-25-running-the-isle.md?plain=1#L66

Change `[Hermes 1.8.3}` to `[Hermes 1.8.3]`

**Comment by tripledoublev** [comment]
Fixed the typo
