### ISSUE TITLE
Switch to using github actions from travis CI

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/hypha.coop#39]
Carrying forward infra goal to simplify deploy toolchain, notes from `2021-07-29` dripline meeting: 

Flow (we’ll use this):

1. Branch feature branch off of master
1. Develop on feature/post branch
1. If feature/post complete (not QA’d), merge to staging. No need to ping for review
1. Fix bugs and test on staging
1. PR from staging to master (ping for review here)
1. How do we deal with publishing to Dweb?

#TODO el to check and see what it will take to deploy to dweb through GH actions.

encypted secrets work: https://docs.github.com/en/actions/reference/encrypted-secrets

**Comment by dcwalk** [comment]
@ASoTNetworks is this good to close?

**Comment by ASoTNetworks** [comment]
This is done and closing.
