### ISSUE TITLE
Add instructions to README for htmlproofer ignore

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/hypha.coop#41]
What to do if htmlproofer is missing?

we replace link with an archive.org link
or use htmlproofer ignore
e.g. we use this for the ipns link ingnore <a href="https://ipfs.distributed.press/ipns/hypha.coop/2021-07-29-dripline.html" data-proofer-ignore>ipns://hypha.coop</a>
https://github.com/gjtorikian/html-proofer#ignoring-content

**Comment by dcwalk** [comment]
Example of where we use it: https://github.com/hyphacoop/hypha.coop/blob/master/_includes/sections/footer.html
the tag to add `data-proofer-ignore`

**Comment by uditvira** [comment]
- add htmlproofer under tech used
- look at how and where we are using htmlproofer (e.g., failing links, dweb links, linkedin etc.)
- add under deployment 
  - document which links are expected to fail
  - what to do to make htmlproofer pass if links fail
    - use an archive.org link if the website no longer exists
    - use ignore code if it's dweb or certain other categories of links that are expected to fail

**Comment by ASoTNetworks** [comment]
Opened PR https://github.com/hyphacoop/hypha.coop/pull/52

**Comment by dcwalk** [comment]
This was merged! Closing
