### ISSUE TITLE
Write data & privacy policy and add to website

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/hypha.coop#5]
In our [`2020-03-30` @hyphacoop/business-planning-wg branding meeting](https://meetings.hypha.coop/2020-03-30-business-planning-branding.html) we identified a mid-term goal of needing **a data & privacy policy.**

**Comment by dcwalk** [comment]
Realizing this might not best live on the website -- could reframe and link to our handbook sections on:
- Working openly (AKA privacy policy)
- How we use data (AKA data policy)

A more human readable take: 
https://www.projectsbyif.com/how-if-uses-data/

**Comment by dcwalk** [comment]
Realizing this might not best live on the website -- could reframe and link to our handbook sections on:
- Working openly (AKA privacy policy)
- How we use data (AKA data policy)

A more human readable take: 
https://www.projectsbyif.com/how-if-uses-data/

**Comment by ASoTNetworks** [comment]
I have opened a PR that addresses the data policy page: https://github.com/hyphacoop/handbook/pull/76

**Comment by benhylau** [comment]
This is done right?

**Comment by dcwalk** [comment]
It's not done / linked from website

**Comment by benhylau** [comment]
Sent PR
