### ISSUE TITLE
Next iteration of website

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/hypha.coop#6]
In our [`2020-03-30` @hyphacoop/business-planning-wg branding meeting](https://meetings.hypha.coop/2020-03-30-business-planning-branding.html) we did some initial identification of needs for the **next iteration of the website**: 

- privacy policy (prioritized) #5 
- identify new potential images (mid-term)
- bios
- multi-page site
- case studies
- blog content
   - also a substack (e.g. OS pattern: Dirk Slater FabRiders)
- bank of our own image assets => hyphacoop/organizing/issues/254

**Comment by patcon** [comment]
`2021-02-25` cleanup: Leaving this open, though @garrying not part of bizdev to chime in

**Comment by dcwalk** [comment]
Feedback from [`2021-06-17`](https://github.com/hyphacoop/organizing-private/blob/12738bb18737ca05872bb61f18b8edab11a5f2b1/meeting-notes/2021-06-17-business-planning.md) call:


#### Website

- What updates do we need?
- Small technical updates #todo dc make gh issue
    - Dripline not responsive
    - Posts should stack
    - Text wieghting and balance
    - More context about what dripline is (e.g. THIS IS A BLOG)
    - footer distributed press link
    - On posts: 
        - alignment of title -- too far to the left
- Bigger tech features
    - Carosoul / announce new blog posts on homepage
    - Retiring 
- "What we do text" out of date
- Revisited next iteration thoughts: https://github.com/hyphacoop/hypha.coop/issues/6
    - Still: bios
    - Still: case studies
- The covid thing?
    - can we archive/sunset thing

- Questions?
    - Headshots
        - can we do non photographic headshots? 
            - dc: yes but visual consistency
    - Think about website content update as AGM outcome

- #todo dc: github issues from above ^

Small tech things for dripline here: https://github.com/hyphacoop/hypha.coop/issues/43

**Comment by benhylau** [comment]
Hi @writerly03 pls see ☝🏽

**Comment by writerly03** [comment]
@kivakiva tagging you here as an FYI
